language: java
before_install:
    - wget -P dependencies/ https://github.com/mrisney/mvar-pdf/blob/master/dependencies/ojdbc8.jar
    - mvn validate

sudo: false # faster builds
script: 
    - "mvn clean install"
after_success:
   - chmod 600 .travis/deploy_key.pem # this key should have push access
   - ssh-add .travis/deploy_key.pem
   - git remote add deploy https://github.com/mrisney/mvar-pdf
   - git push deploy
